CREATE SEQUENCE todo_sequence START 1;

CREATE TABLE TODO (
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(255),
  OWNER VARCHAR(255),
  PRIORITY VARCHAR(255)
);

INSERT INTO TODO (name, owner, priority)
VALUES ('First Todo list', 'Adi', 'High');